otel:
  propagators:
    - tracecontext
  resource:
    attributes:
      deployment.environment: local
      service:
        name: petclinic
        namespace: spring
  instrumentation:
    micrometer:
      enabled: true
      
management:
  tracing:
    sampling:
      probability: 1.0
